### ISSUE TITLE
No so much an issue just adding a new score

### ISSUE THREAD

**Issue by Ubique88** [alexdedyura/cpu-benchmark#11]
Python CPU Benchmark by Alex Dedyura (Windows, macOS(Darwin), Linux)
CPU: AMD Ryzen 9 7950X 16-Core Processor
Arch: AMD64
OS: Windows

Benchmarking:

Time: 12.738s
Time: 13.212s
Time: 13.032s
Time: 13.021s
Time: 13.013s
Time: 13.176s
Time: 13.029s
Time: 13.033s
Time: 13.03s
Time: 13.19s
Average (from 10 repeats): 13.047s

**Comment by tc0nn** [comment]
Would be nice if someone could collect these results so we could compare:
CPU: Apple M1 Max
Arch: arm64
OS: Darwin

Benchmarking: 

Time: 15.498s
Time: 15.353s
Time: 15.347s
Time: 15.384s
Time: 15.351s
Time: 15.351s
Time: 15.366s
Time: 15.38s
Time: 15.375s
Time: 15.362s
Average (from 10 repeats): 15.377s

CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Arch: x86_64
OS: Darwin

Benchmarking: 

Time: 29.254s
Time: 29.737s
Time: 29.344s
Time: 28.886s
Time: 27.9s
Time: 27.842s
Time: 28.97s
Time: 28.183s
Time: 27.509s
Time: 28.888s
Average (from 10 repeats): 28.651s
