### ISSUE TITLE
Misleading name

### ISSUE THREAD

**Issue by Arsnck** [alexdedyura/cpu-benchmark#23]
Benchmark doesn't even calculate pi. Update the readme to be less misleading.

<sub><a href="https://huly.app/guest/zxcloud?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNmOWI4Y2QyZWY0Y2JjYzQ2Nzk1NWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctb2ZmaWNpYWx0aGVhLXp4Y2xvdWQtNjcwNmVjMDAtMDAwODk4MjVjOS00ZGI2NzIifQ._F4hulsdpN_3zNWyP_I5AXx6DubMVdF8zkO1soVo9qo">Huly&reg;: <b>HULY-27</b></a></sub>

**Comment by jacksonmatheson** [comment]
Why wouldn't you fix this? It's not that big of a deal that you perform your benchmark a different way, but to lie about it is poor form.
