### ISSUE TITLE
Apple M4 Max

### ISSUE THREAD

**Issue by seatonjiang** [alexdedyura/cpu-benchmark#24]
Average (from 10 repeats): 12.144s

![image](https://github.com/user-attachments/assets/c66f9bba-a773-4e73-885c-a5556292e2a3)

<sub><a href="https://huly.app/guest/zxcloud?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRkYTViM2QyZWY0Y2JjYzQ2ZDYxZjgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctb2ZmaWNpYWx0aGVhLXp4Y2xvdWQtNjcwNmVjMDAtMDAwODk4MjVjOS00ZGI2NzIifQ.4Ha6NYTHwcxv3RD_4MCVkBOH3Ju2QRIfz2FTwYowax8">Huly&reg;: <b>HULY-28</b></a></sub>

**Comment by alexdedyura** [comment]
Done, M4 Max Beast 🔥
