### ISSUE TITLE
Comparison Windows / WSL

### ISSUE THREAD

**Issue by skjerns** [alexdedyura/cpu-benchmark#4]
I tried this out on my computer running Windows and on WSL2 using Ubuntu, both on Python 3.10

```
AMD Ryzen 9 3900X 12-Core Processor
Windows: 38.707s
WSL2: 24.703s
```

Probably due to different BLAS libraries being used in both OSs. This will bias the results either way I guess, and changing ATLAS/BLAS will change the scores on the same CPU

**Comment by alexdedyura** [comment]
It is very interesting. I got a similar situation, my processor in Linux (Debian 12) performed calculations faster than on Windows 11. In the near future, I plan to rework the code and make it multithreaded, as well as make an option with a GUI and a more accurate definition of hardware.
