### ISSUE TITLE
Idea: Better timing details

### ISSUE THREAD

**Issue by Barry1** [alexdedyura/cpu-benchmark#5]
Cool tool. THX.
I propose (PR to come in a few seconds) to better use `time.perf_counter` instead of `time.time`. That brings the following benefits:

* `time.perf_counter` is monitonic (not influenced by DST or leap seconds)
* `time.perf_counter` has a better resolution

Best regards

Bastian

**Comment by alexdedyura** [comment]
Сделано

**Comment by alexdedyura** [comment]
Done it

**Comment by alexdedyura** [comment]
Done it
